(function(){
'use strict';
const canvas=document.getElementById('hydraulicDiagram'),ctx=canvas.getContext('2d');
const grid=document.getElementById('componentGrid'),nameEl=document.getElementById('componentName'),purposeEl=document.getElementById('componentPurpose'),operationEl=document.getElementById('componentOperation');
const stateCard=document.getElementById('stateCard'),stateTitle=document.getElementById('stateTitle'),stateText=document.getElementById('stateText'),stateImpacts=document.getElementById('stateImpacts'),failButton=document.getElementById('failSelected'),restoreButton=document.getElementById('restoreAll'),failureCount=document.getElementById('failureCount');
const modeButtons=[...document.querySelectorAll('[data-mode]')];
const C={bg:'#020403',panel:'#0b100d',metal:'#627069',metal2:'#26312b',white:'#edf5ef',muted:'#829188',green:'#42e56c',blue:'#51b7ff',yellow:'#ffd43b',amber:'#ffb327',red:'#ff5757',cyan:'#45d7ec',dim:'#26312a'};
const components={
 overview:{name:'HYDRAULIC SYSTEM OVERVIEW',group:'SYSTEM',purpose:'Three independent hydraulic systems distribute 3,000 PSI power to flight controls and aircraft services.',operation:'Each system has its own reservoir. Fluid cannot transfer between systems; the PTU transfers mechanical power only.',ref:'DSC-29-10-10'},
 greenReservoir:{name:'GREEN RESERVOIR',group:'GREEN',purpose:'Stores and supplies green hydraulic fluid.',operation:'Loss, low level or low air pressure makes the green pumps unable to sustain pressure.',ref:'DSC-29-10-10/20'},
 greenFire:{name:'ENG 1 FIRE SHUTOFF VALVE',group:'GREEN',purpose:'Isolates reservoir supply upstream of the engine 1 pump.',operation:'The ENG 1 FIRE pushbutton closes this valve. Green can still be pressurised by the PTU when its reservoir and downstream circuit are healthy.',ref:'DSC-29-10-20'},
 eng1Pump:{name:'ENG 1 PUMP',group:'GREEN',purpose:'Engine 1 driven pump; the normal green-system pressure source.',operation:'With engine 1 running and the fire valve open it supplies 3,000 PSI. A pump failure normally makes the PTU transfer yellow-system power to green.',ref:'DSC-29-10-20'},
 greenAccumulator:{name:'GREEN ACCUMULATOR',group:'GREEN',purpose:'Covers transient demand and helps maintain steady pressure.',operation:'It smooths pressure; it is not modelled as a sustained replacement for a failed pump.',ref:'DSC-29-10-20'},
 greenPriority:{name:'GREEN PRIORITY VALVE',group:'GREEN',purpose:'Protects essential users by cutting off heavy green-system loads when pressure is low.',operation:'A failed/closed valve removes landing gear and slat/flap supply while other pressurised green users remain available.',ref:'DSC-29-10-20/30'},
 greenLeak:{name:'GREEN LEAK MEASUREMENT VALVE',group:'GREEN',purpose:'Isolates the green supply to primary flight controls for maintenance leakage checks.',operation:'Closing or failing the valve removes the green contribution to the primary flight controls.',ref:'DSC-29-20'},
 greenCircuit:{name:'GREEN PRESSURE CIRCUIT',group:'GREEN',purpose:'Distributes green pressure to its allocated aircraft users.',operation:'A circuit failure represents a total green-system pressure loss regardless of source.',ref:'DSC-29-10-30'},
 blueReservoir:{name:'BLUE RESERVOIR',group:'BLUE',purpose:'Stores and supplies blue hydraulic fluid.',operation:'Low fluid or reservoir pressurisation prevents both the electric and RAT pumps from sustaining blue pressure.',ref:'DSC-29-10-10/20'},
 blueElec:{name:'BLUE ELECTRIC PUMP',group:'BLUE',purpose:'The normal blue-system pressure source.',operation:'In AUTO with AC power, it runs in flight and on the ground when one engine runs or BLUE PUMP OVRD is selected.',ref:'DSC-29-20'},
 rat:{name:'RAT HYDRAULIC PUMP',group:'BLUE',purpose:'Emergency blue-system pump driven by the ram air turbine.',operation:'The RAT deploys automatically if AC BUS 1 and AC BUS 2 are both lost, or manually from the overhead panel. RAT pressure is 2,500 PSI.',ref:'DSC-29-10-20'},
 blueAccumulator:{name:'BLUE ACCUMULATOR',group:'BLUE',purpose:'Covers transient blue-system demand.',operation:'It smooths demand but is not a sustained replacement for the electric or RAT pump.',ref:'DSC-29-10-20'},
 bluePriority:{name:'BLUE PRIORITY VALVE',group:'BLUE',purpose:'Cuts off heavy blue-system users when pressure is low.',operation:'A failed/closed valve removes emergency-generator and slat supply while preserving pressurised primary-control services.',ref:'DSC-29-10-20/30'},
 blueLeak:{name:'BLUE LEAK MEASUREMENT VALVE',group:'BLUE',purpose:'Isolates blue pressure from the primary flight controls for maintenance.',operation:'Closing or failing the valve removes the blue contribution to the primary flight controls.',ref:'DSC-29-20'},
 blueCircuit:{name:'BLUE PRESSURE CIRCUIT',group:'BLUE',purpose:'Distributes blue pressure to allocated users.',operation:'A circuit failure represents complete blue pressure loss, including loss of hydraulically driven emergency generation.',ref:'DSC-29-10-30'},
 yellowReservoir:{name:'YELLOW RESERVOIR',group:'YELLOW',purpose:'Stores and supplies yellow hydraulic fluid.',operation:'Loss, low level or low air pressure prevents engine, electric and hand-pump supply from operating normally.',ref:'DSC-29-10-10/20'},
 yellowFire:{name:'ENG 2 FIRE SHUTOFF VALVE',group:'YELLOW',purpose:'Isolates reservoir supply upstream of the engine 2 pump.',operation:'The ENG 2 FIRE pushbutton closes this valve. PTU or electric-pump pressurisation can remain available downstream when the reservoir is healthy.',ref:'DSC-29-10-20'},
 eng2Pump:{name:'ENG 2 PUMP',group:'YELLOW',purpose:'Engine 2 driven pump; the normal yellow-system pressure source.',operation:'With engine 2 running and the fire valve open it supplies 3,000 PSI. A failure normally lets the PTU transfer green-system power to yellow.',ref:'DSC-29-10-20'},
 yellowElec:{name:'YELLOW ELECTRIC PUMP',group:'YELLOW',purpose:'Auxiliary yellow pressure source for ground operation and cargo doors.',operation:'Selected manually or activated by the cargo-door selector. Cargo-door operation inhibits other yellow functions except alternate braking and engine 2 reverse.',ref:'DSC-29-20'},
 handPump:{name:'YELLOW HAND PUMP',group:'YELLOW',purpose:'Pressurises the cargo-door circuit when no electrical power is available.',operation:'It is a local cargo-door facility, not a replacement source for all yellow-system users.',ref:'DSC-29-10-20'},
 yellowAccumulator:{name:'YELLOW ACCUMULATOR',group:'YELLOW',purpose:'Covers transient yellow-system demand.',operation:'It smooths demand but is not a sustained replacement for a pressure source.',ref:'DSC-29-10-20'},
 yellowPriority:{name:'YELLOW PRIORITY VALVE',group:'YELLOW',purpose:'Cuts off heavy yellow-system users when pressure is low.',operation:'A failed/closed valve removes flap supply while preserving pressurised priority users.',ref:'DSC-29-10-20/30'},
 yellowLeak:{name:'YELLOW LEAK MEASUREMENT VALVE',group:'YELLOW',purpose:'Isolates yellow pressure from the primary flight controls for maintenance.',operation:'Closing or failing the valve removes the yellow contribution to primary flight controls.',ref:'DSC-29-20'},
 yellowCircuit:{name:'YELLOW PRESSURE CIRCUIT',group:'YELLOW',purpose:'Distributes yellow pressure to allocated aircraft users.',operation:'A circuit failure represents a total yellow-system pressure loss regardless of source.',ref:'DSC-29-10-30'},
 ptu:{name:'POWER TRANSFER UNIT',group:'TRANSFER',purpose:'Bidirectionally transfers mechanical power between green and yellow without mixing fluid.',operation:'In AUTO it runs when pressure difference exceeds 500 PSI. It is inhibited during first engine start and tested during second engine start.',ref:'DSC-29-10-20 / DSC-29-20'},
 greenHeavy:{name:'GREEN HEAVY-LOAD USERS',group:'USERS',purpose:'Landing gear and green slat/flap supply downstream of the green priority valve.',operation:'Available only with green pressure and an open/healthy green priority valve.',ref:'DSC-29-10-30'},
 greenUsers:{name:'GREEN PRIORITY USERS',group:'USERS',purpose:'Includes engine 1 reverse, normal braking and green-powered flight-control actuators.',operation:'Remain supplied with green pressure; the primary-control contribution also depends on the leak measurement valve.',ref:'DSC-29-10-30'},
 blueHeavy:{name:'BLUE HEAVY-LOAD USERS',group:'USERS',purpose:'Emergency generator and blue slat supply downstream of the blue priority valve.',operation:'Loss removes the blue hydraulic drive to the emergency generator and the blue slat channel.',ref:'DSC-29-10-30'},
 blueUsers:{name:'BLUE PRIORITY USERS',group:'USERS',purpose:'Blue-powered rudder, elevator, aileron, spoiler and wing-tip-brake actuators.',operation:'Depend on blue pressure and the blue leak measurement valve.',ref:'DSC-29-10-30'},
 yellowHeavy:{name:'YELLOW HEAVY-LOAD USERS',group:'USERS',purpose:'Yellow flap supply downstream of the yellow priority valve.',operation:'Available only with yellow pressure and a healthy/open yellow priority valve.',ref:'DSC-29-10-30'},
 yellowUsers:{name:'YELLOW PRIORITY USERS',group:'USERS',purpose:'Includes nosewheel steering, alternate/parking brake, engine 2 reverse and yellow-powered flight-control actuators.',operation:'Remain supplied with yellow pressure; primary controls also depend on the leak measurement valve.',ref:'DSC-29-10-30'},
 cargoDoor:{name:'CARGO DOOR HYDRAULICS',group:'USERS',purpose:'Uses yellow hydraulic power for cargo-door operation.',operation:'The yellow electric pump starts automatically with the cargo-door selector. The hand pump permits operation without electrical power.',ref:'DSC-29-10-20 / DSC-29-20'}
};
const presets={
 normal:{title:'NORMAL CONFIGURATION',text:'Engine-driven pumps pressurise green and yellow; the blue electric pump pressurises blue.',config:{eng1:true,eng2:true,blueElec:true,yellowElec:false,rat:false,hand:false},fail:[]},
 eng1:{title:'ENG 1 PUMP FAILURE',text:'Green loses its engine-driven source; the PTU transfers power from yellow to green.',config:{eng1:true,eng2:true,blueElec:true,yellowElec:false,rat:false,hand:false},fail:['eng1Pump']},
 eng2:{title:'ENG 2 PUMP FAILURE',text:'Yellow loses its engine-driven source; the PTU transfers power from green to yellow.',config:{eng1:true,eng2:true,blueElec:true,yellowElec:false,rat:false,hand:false},fail:['eng2Pump']},
 ptuoff:{title:'PTU FAILURE',text:'Green and yellow remain independent; neither can back up the other after a pump loss.',config:{eng1:true,eng2:true,blueElec:true,yellowElec:false,rat:false,hand:false},fail:['ptu']},
 bluepump:{title:'BLUE ELECTRIC PUMP FAILURE',text:'The normal blue source is lost. The RAT is not deployed in this preset, so blue pressure is unavailable.',config:{eng1:true,eng2:true,blueElec:true,yellowElec:false,rat:false,hand:false},fail:['blueElec']},
 yellowpump:{title:'YELLOW ELECTRIC PUMP FAILURE',text:'The yellow electric auxiliary source is unavailable; engine 2 and the PTU can still pressurise yellow.',config:{eng1:true,eng2:true,blueElec:true,yellowElec:true,rat:false,hand:false},fail:['yellowElec']},
 rat:{title:'RAT / EMERGENCY CONFIGURATION',text:'Both engine-driven sources and the blue electric pump are lost; the deployed RAT supplies blue at 2,500 PSI.',config:{eng1:false,eng2:false,blueElec:false,yellowElec:false,rat:true,hand:false},fail:[]}
};
let activeMode='normal',config={...presets.normal.config},failed=new Set(),selected='overview',hit=[],W=900,H=720,scale=1;
const healthy=id=>!failed.has(id);
function evaluate(){
 const greenReservoir=healthy('greenReservoir'),yellowReservoir=healthy('yellowReservoir'),blueReservoir=healthy('blueReservoir');
 const greenDirect=config.eng1&&healthy('eng1Pump')&&healthy('greenFire')&&greenReservoir&&healthy('greenCircuit');
 const yellowEngine=config.eng2&&healthy('eng2Pump')&&healthy('yellowFire')&&yellowReservoir&&healthy('yellowCircuit');
 const yellowElectric=config.yellowElec&&healthy('yellowElec')&&yellowReservoir&&healthy('yellowCircuit');
 const yellowDirect=yellowEngine||yellowElectric;
 let green=greenDirect,yellow=yellowDirect,ptuDirection='';
 if(healthy('ptu')){
   if(!green&&yellow&&greenReservoir&&healthy('greenCircuit')){green=true;ptuDirection='YELLOW → GREEN'}
   else if(!yellow&&green&&yellowReservoir&&healthy('yellowCircuit')){yellow=true;ptuDirection='GREEN → YELLOW'}
 }
 const blueElectric=config.blueElec&&healthy('blueElec')&&blueReservoir&&healthy('blueCircuit');
 const ratActive=config.rat&&healthy('rat')&&blueReservoir&&healthy('blueCircuit');
 const blue=blueElectric||ratActive;
 const pressure={green:green?3000:0,blue:blue?(ratActive&&!blueElectric?2500:3000):0,yellow:yellow?3000:0};
 const users={
   greenHeavy:green&&healthy('greenPriority')&&healthy('greenHeavy'),greenUsers:green&&healthy('greenUsers'),greenControls:green&&healthy('greenLeak'),
   blueHeavy:blue&&healthy('bluePriority')&&healthy('blueHeavy'),blueUsers:blue&&healthy('blueUsers'),blueControls:blue&&healthy('blueLeak'),
   yellowHeavy:yellow&&healthy('yellowPriority')&&healthy('yellowHeavy'),yellowUsers:yellow&&healthy('yellowUsers'),yellowControls:yellow&&healthy('yellowLeak'),
   cargoDoor:(yellow||config.hand&&healthy('handPump')&&yellowReservoir)&&healthy('cargoDoor')
 };
 return{green,blue,yellow,greenDirect,yellowDirect,blueElectric,ratActive,ptuDirection,pressure,users};
}
function impacts(s){const out=[];if(!s.green)out.push('Green pressure lost: landing gear, normal brakes, ENG 1 reverse and the green flight-control contribution are unavailable.');else if(s.ptuDirection==='YELLOW → GREEN')out.push('PTU is transferring yellow-system power to restore green pressure; hydraulic fluid remains separate.');if(!s.blue)out.push('Blue pressure lost: the blue flight-control contribution and hydraulically driven emergency generator are unavailable.');else if(s.ratActive)out.push('RAT supplies blue at 2,500 PSI rather than the normal 3,000 PSI.');if(!s.yellow)out.push('Yellow pressure lost: nosewheel steering, alternate/parking braking, ENG 2 reverse and the yellow flight-control contribution are unavailable.');else if(s.ptuDirection==='GREEN → YELLOW')out.push('PTU is transferring green-system power to restore yellow pressure; hydraulic fluid remains separate.');if(s.green&&!s.users.greenHeavy)out.push('Green priority valve has isolated landing gear and slat/flap heavy loads.');if(s.blue&&!s.users.blueHeavy)out.push('Blue priority valve has isolated emergency-generator and slat heavy loads.');if(s.yellow&&!s.users.yellowHeavy)out.push('Yellow priority valve has isolated flap heavy loads.');if(!s.users.greenControls||!s.users.blueControls||!s.users.yellowControls)out.push('At least one hydraulic contribution to the primary flight controls is isolated; remaining systems continue to power their allocated actuators.');if(!out.length)out.push('All three systems are pressurised and all displayed user groups are available.');return out}
function statusFor(id,s){if(failed.has(id))return'fault';if(id==='overview')return'normal';if(id==='eng1Pump')return s.greenDirect?'active':config.eng1?'caution':'standby';if(id==='eng2Pump')return s.yellowDirect?'active':config.eng2?'caution':'standby';if(id==='blueElec')return s.blueElectric?'active':config.blueElec?'caution':'standby';if(id==='yellowElec')return config.yellowElec&&s.yellowDirect?'active':'standby';if(id==='rat')return s.ratActive?'active':'standby';if(id==='handPump')return config.hand?'active':'standby';if(id==='ptu')return s.ptuDirection?'active':'standby';if(id==='greenCircuit')return s.green?'active':'caution';if(id==='blueCircuit')return s.blue?'active':'caution';if(id==='yellowCircuit')return s.yellow?'active':'caution';if(id==='greenHeavy')return s.users.greenHeavy?'active':'inactive';if(id==='greenUsers')return s.users.greenUsers?'active':'inactive';if(id==='blueHeavy')return s.users.blueHeavy?'active':'inactive';if(id==='blueUsers')return s.users.blueUsers?'active':'inactive';if(id==='yellowHeavy')return s.users.yellowHeavy?'active':'inactive';if(id==='yellowUsers')return s.users.yellowUsers?'active':'inactive';if(id==='cargoDoor')return s.users.cargoDoor?'active':'inactive';return'normal'}
function colorFor(status,circuit){if(status==='fault')return C.red;if(status==='inactive'||status==='caution')return C.amber;if(circuit&&C[circuit])return C[circuit];if(status==='standby')return C.muted;return C.green}
function font(n){return Math.max(9,Math.round(n*scale))+'px ui-monospace,Menlo,Consolas,monospace'}
function label(t,x,y,color=C.white,n=13,align='center'){ctx.save();ctx.fillStyle=color;ctx.font=font(n);ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillText(t,x,y);ctx.restore()}
function glowLine(points,color,on=true,dash=[]){ctx.save();ctx.strokeStyle=on?color:C.dim;ctx.lineWidth=on?3:1.3;ctx.setLineDash(on?dash:[5,6]);if(on){ctx.shadowColor=color;ctx.shadowBlur=7}ctx.beginPath();ctx.moveTo(points[0][0],points[0][1]);for(let i=1;i<points.length;i++)ctx.lineTo(points[i][0],points[i][1]);ctx.stroke();ctx.restore()}
function bevel(x,y,w,h,title,value,status='normal',circuit='',id=''){const color=colorFor(status,circuit);ctx.save();let g=ctx.createLinearGradient(x,y,x,y+h);g.addColorStop(0,'#17211b');g.addColorStop(.5,'#080c09');g.addColorStop(1,'#101712');ctx.fillStyle=g;ctx.fillRect(x,y,w,h);ctx.strokeStyle=color;ctx.lineWidth=status==='fault'?2.5:1.4;if(status==='active'){ctx.shadowColor=color;ctx.shadowBlur=7}ctx.strokeRect(x+.5,y+.5,w-1,h-1);ctx.strokeStyle='rgba(255,255,255,.2)';ctx.beginPath();ctx.moveTo(x+2,y+2);ctx.lineTo(x+w-2,y+2);ctx.stroke();ctx.restore();label(title,x+w/2,y+14,status==='fault'?C.red:C.white,11);if(value)label(value,x+w/2,y+h-14,color,11);if(selected===id){ctx.save();ctx.strokeStyle=C.cyan;ctx.lineWidth=2;ctx.setLineDash([5,4]);ctx.strokeRect(x-4,y-4,w+8,h+8);ctx.restore()}if(id)hit.push({id,x,y,w,h})}
function reservoir(x,y,w,h,name,circuit,id,s){const status=statusFor(id,s),color=colorFor(status,circuit);ctx.save();let g=ctx.createLinearGradient(x,y,x,y+h);g.addColorStop(0,'#27322d');g.addColorStop(.58,'#111813');g.addColorStop(.6,color+'55');g.addColorStop(1,color+'22');ctx.fillStyle=g;ctx.fillRect(x,y,w,h);ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.strokeRect(x,y,w,h);ctx.restore();label(name,x+w/2,y+16,C.white,10);label(failed.has(id)?'LOW / FAILED':'NORM',x+w/2,y+h-15,color,10);if(selected===id){ctx.strokeStyle=C.cyan;ctx.strokeRect(x-4,y-4,w+8,h+8)}hit.push({id,x,y,w,h})}
function disc(x,y,r,title,status,circuit,id){const color=colorFor(status,circuit);ctx.save();let g=ctx.createRadialGradient(x-r*.35,y-r*.4,2,x,y,r);g.addColorStop(0,'#79867f');g.addColorStop(.35,'#27312c');g.addColorStop(1,'#020403');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=status==='fault'?3:2;if(status==='active'){ctx.shadowColor=color;ctx.shadowBlur=9}ctx.stroke();ctx.restore();label(title,x,y,color,10);if(selected===id){ctx.strokeStyle=C.cyan;ctx.setLineDash([4,3]);ctx.strokeRect(x-r-5,y-r-5,r*2+10,r*2+10);ctx.setLineDash([])}hit.push({id,x:x-r,y:y-r,w:r*2,h:r*2})}
function draw(){W=Math.max(320,canvas.clientWidth||700);H=Math.round(W*.78);H=Math.max(520,Math.min(760,H));scale=Math.max(.73,Math.min(1.12,W/850));const dpr=Math.min(2,devicePixelRatio||1);canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle=C.bg;ctx.fillRect(0,0,W,H);hit=[];const s=evaluate(),compact=W<560;const x={green:W*.18,blue:W*.5,yellow:W*.82},top=38,resY=H*.73,resW=Math.min(130,W*.2),resH=72,pumpY=H*.56,busY=H*.32,userY=H*.12;
 label('HYDRAULIC GENERATION & DISTRIBUTION',18,17,C.white,14,'left');label('SELECT ANY BOX OR DISC',W-18,17,C.cyan,10,'right');
 ['green','blue','yellow'].forEach(k=>{const col=C[k],on=s[k];glowLine([[x[k],resY],[x[k],pumpY+30],[x[k],busY]],col,on);glowLine([[x[k],busY],[x[k],userY+70]],col,on);bevel(x[k]-resW*.52,busY-18,resW*1.04,36,k.toUpperCase()+' SYSTEM',s.pressure[k].toLocaleString()+' PSI',on?'active':'caution',k,k+'Circuit')});
 reservoir(x.green-resW/2,resY,resW,resH,compact?'GREEN RSVR':'GREEN RESERVOIR','green','greenReservoir',s);reservoir(x.blue-resW/2,resY,resW,resH,compact?'BLUE RSVR':'BLUE RESERVOIR','blue','blueReservoir',s);reservoir(x.yellow-resW/2,resY,resW,resH,compact?'YELLOW RSVR':'YELLOW RESERVOIR','yellow','yellowReservoir',s);
 bevel(x.green-resW*.82,resY-67,resW*.62,38,'FIRE VALVE',healthy('greenFire')?'OPEN':'CLOSED',statusFor('greenFire',s),'green','greenFire');bevel(x.yellow+resW*.2,resY-67,resW*.62,38,'FIRE VALVE',healthy('yellowFire')?'OPEN':'CLOSED',statusFor('yellowFire',s),'yellow','yellowFire');
 const pumpOffset=compact?27:42,pumpRadius=compact?23:31;disc(x.green,pumpY,compact?27:33,'ENG 1',statusFor('eng1Pump',s),'green','eng1Pump');disc(x.blue-pumpOffset,pumpY,pumpRadius,'ELEC',statusFor('blueElec',s),'blue','blueElec');disc(x.blue+pumpOffset,pumpY,pumpRadius,'RAT',statusFor('rat',s),'blue','rat');disc(x.yellow-pumpOffset,pumpY,pumpRadius,'ENG 2',statusFor('eng2Pump',s),'yellow','eng2Pump');disc(x.yellow+pumpOffset,pumpY,pumpRadius,'ELEC',statusFor('yellowElec',s),'yellow','yellowElec');
 const ptuRadius=compact?30:38;disc(W*.5,H*.43,ptuRadius,'PTU',statusFor('ptu',s),s.ptuDirection==='YELLOW → GREEN'?'green':s.ptuDirection==='GREEN → YELLOW'?'yellow':'','ptu');glowLine([[x.green,busY+18],[x.green,H*.43],[W*.5-ptuRadius,H*.43]],C.green,!!s.ptuDirection);glowLine([[W*.5+ptuRadius,H*.43],[x.yellow,H*.43],[x.yellow,busY+18]],C.yellow,!!s.ptuDirection);if(s.ptuDirection)label(s.ptuDirection,W*.5,H*.43+ptuRadius+14,C.green,9);
 const boxW=Math.min(155,W*.25),gap=7;bevel(x.green-boxW/2,userY,boxW,42,compact?'GEAR / SLATS':'LANDING GEAR / SLATS-FLAPS',s.users.greenHeavy?'AVAILABLE':'LOST',statusFor('greenHeavy',s),'green','greenHeavy');bevel(x.green-boxW/2,userY+49,boxW,42,compact?'BRAKES / REV 1':'BRAKES / REV 1 / CONTROLS',s.users.greenUsers?'AVAILABLE':'LOST',statusFor('greenUsers',s),'green','greenUsers');bevel(x.blue-boxW/2,userY,boxW,42,compact?'EMER GEN':'EMER GEN / SLATS',s.users.blueHeavy?'AVAILABLE':'LOST',statusFor('blueHeavy',s),'blue','blueHeavy');bevel(x.blue-boxW/2,userY+49,boxW,42,compact?'FLT CONTROLS':'FLIGHT CONTROLS',s.users.blueControls?'AVAILABLE':'ISOLATED',s.users.blueControls?'active':'inactive','blue','blueUsers');bevel(x.yellow-boxW/2,userY,boxW,42,'FLAPS',s.users.yellowHeavy?'AVAILABLE':'LOST',statusFor('yellowHeavy',s),'yellow','yellowHeavy');bevel(x.yellow-boxW/2,userY+49,boxW,42,compact?'NWS / BRK / REV 2':'NWS / BRAKES / REV 2',s.users.yellowUsers?'AVAILABLE':'LOST',statusFor('yellowUsers',s),'yellow','yellowUsers');
 if(!compact){const auxY=H*.9,auxGap=7,auxW=(W-auxGap*6)/5;[['greenAccumulator','GREEN ACCUM','green',healthy('greenAccumulator')?'READY':'FAILED'],['blueAccumulator','BLUE ACCUM','blue',healthy('blueAccumulator')?'READY':'FAILED'],['yellowAccumulator','YELLOW ACCUM','yellow',healthy('yellowAccumulator')?'READY':'FAILED'],['handPump','HAND PUMP','yellow',healthy('handPump')?'READY':'FAILED'],['cargoDoor','CARGO DOOR','yellow',s.users.cargoDoor?'AVAILABLE':'LOST']].forEach((a,i)=>bevel(auxGap+(auxW+auxGap)*i,auxY,auxW,42,a[1],a[3],statusFor(a[0],s),a[2],a[0]))}
 canvas.setAttribute('aria-label','A320 hydraulic trainer. Green '+s.pressure.green+' PSI, blue '+s.pressure.blue+' PSI, yellow '+s.pressure.yellow+' PSI.');
}
function updateInfo(){const s=evaluate(),d=components[selected]||components.overview,status=statusFor(selected,s),isFailed=failed.has(selected);nameEl.textContent=d.name;purposeEl.textContent=d.purpose;operationEl.textContent=d.operation+' · '+d.ref;const list=impacts(s);stateTitle.textContent=isFailed?'COMPONENT FAILED':presets[activeMode]?.title||'CUSTOM CONFIGURATION';stateText.textContent=isFailed?d.name+' has been removed from the hydraulic model. Downstream consequences are recalculated immediately.':presets[activeMode]?.text||'Custom component failures are active.';stateImpacts.replaceChildren();list.slice(0,6).forEach(t=>{const li=document.createElement('li');li.textContent=t;stateImpacts.appendChild(li)});stateCard.className='state '+(isFailed?'fault':list.length>1?'caution':'');failButton.textContent=isFailed?'RESTORE SELECTED':'FAIL SELECTED';failButton.disabled=selected==='overview';failureCount.textContent=failed.size?failed.size+' ACTIVE COMPONENT FAILURE'+(failed.size===1?'':'S'):'NO ACTIVE COMPONENT FAILURES'}
function updateGrid(){const s=evaluate();grid.replaceChildren();Object.entries(components).filter(([id])=>id!=='overview').forEach(([id,d])=>{const b=document.createElement('button');b.className='component'+(failed.has(id)?' failed':'')+(selected===id?' selected':'');b.innerHTML='<strong></strong><span></span>';b.querySelector('strong').textContent=d.name;b.querySelector('span').textContent=failed.has(id)?'FAILED — TAP TO RESTORE':statusFor(id,s).toUpperCase()+' — TAP TO FAIL';b.addEventListener('click',()=>{if(selected===id)toggleFail(id);else{selected=id;render()}});grid.appendChild(b)})}
function render(){draw();updateInfo();updateGrid();modeButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===activeMode)))}
function toggleFail(id=selected){if(!components[id]||id==='overview')return;if(failed.has(id))failed.delete(id);else failed.add(id);activeMode='';render()}
function loadMode(id){const p=presets[id];if(!p)return;activeMode=id;config={...p.config};failed=new Set(p.fail);selected='overview';render()}
canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),px=(e.clientX-r.left)*W/r.width,py=(e.clientY-r.top)*H/r.height;const h=[...hit].reverse().find(a=>px>=a.x&&px<=a.x+a.w&&py>=a.y&&py<=a.y+a.h);if(h){selected=h.id;render()}});canvas.addEventListener('dblclick',e=>{e.preventDefault();if(selected!=='overview')toggleFail(selected)});failButton.addEventListener('click',()=>toggleFail());restoreButton.addEventListener('click',()=>loadMode('normal'));modeButtons.forEach(b=>b.addEventListener('click',()=>loadMode(b.dataset.mode)));if('ResizeObserver'in window)new ResizeObserver(draw).observe(canvas.parentElement);else addEventListener('resize',draw);
window.A320HydraulicTrainer={loadMode,selectComponent:id=>{if(components[id]){selected=id;render()}},failComponent:id=>{if(components[id]&&id!=='overview'){failed.add(id);activeMode='';render()}},restoreComponent:id=>{failed.delete(id);render()},restoreAll:()=>loadMode('normal'),getState:()=>({mode:activeMode,failures:[...failed],...evaluate()}),getComponents:()=>Object.keys(components).filter(id=>id!=='overview')};
const scenario=typeof location!=="undefined"?new URLSearchParams(location.search).get("scenario"):"";
loadMode({eng1:"eng1",eng2:"eng2",dual:"rat"}[scenario]||"normal");
})();

