'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STORE='qantas-a321p2f-study-v1';
let manuals,questions,patterns,drills,activeRun=null,flowRun=null,readerState=null,searchGeneration=0;
let privateManuals,readerGeneration=0;
const loadJson=async path=>{const r=await fetch(path);if(!r.ok)throw Error('Could not load '+path);return r.json();};
let saved;try{saved=JSON.parse(localStorage.getItem(STORE)||'{}');}catch{saved={};}
if(!saved||typeof saved!=='object'||Array.isArray(saved))saved={};
for(const key of ['questions','chapters','drills'])if(!saved[key]||typeof saved[key]!=='object')saved[key]={};
function persist(){try{localStorage.setItem(STORE,JSON.stringify(saved));}catch{toast('Progress could not be saved on this device.');}}
function toast(msg){$('toast').textContent=msg;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').textContent='',4500);}
function shuffle(items){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
function pageButton(doc,page,label){return `<button class="page-button" data-source="${doc}" data-page="${page}">${esc(label||doc+' · PDF p. '+page)}</button>`;}
function sourceButtons(q){return `<div class="source">${esc(q.ref)} · ${esc(q.applicability?.includes('ALL')?'A321P2F':q.applicability?.join(', ')||'See page effectivity')}<div class="source-row">${q.pages.map(p=>pageButton(q.manual,p)).join('')}</div></div>`;}
function header(kicker,title,description,actions=''){return `<div class="section-head"><div><div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1><p class="muted">${esc(description)}</p></div>${actions?`<div class="actions">${actions}</div>`:''}</div>`;}
function chapters(doc,start,end,level){return manuals[doc].outline.filter(x=>x.page>=start&&x.page<=end&&x.level===level&&!/Preliminary|Contents|Highlights|Effective/.test(x.title));}
const studyAreas={flows:'Flow patterns',normal:'Normal procedures',abnormal:'Abnormal procedures',limitations:'Limitations',systems:'Aircraft systems'};
function deskIcon(name){
 const paths={flow:'<rect x="3" y="3" width="6" height="6" rx="1.5"/><rect x="15" y="15" width="6" height="6" rx="1.5"/><path d="M9 6h6a3 3 0 0 1 3 3v6M6 9v9h9"/>',procedure:'<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4V2h6v2M9 10h6M9 14h6M9 18h3"/>',limits:'<path d="M5 19V9M12 19V5M19 19V12M3 9h4M10 5h4M17 12h4"/>',book:'<path d="M12 5v15M12 5C9 3 5 3 2 4v15c3-1 7-1 10 1 3-2 7-2 10-1V4c-3-1-7-1-10 1Z"/>',systems:'<circle cx="12" cy="12" r="3"/><path d="M12 2v4M12 18v4M2 12h4M18 12h4M5 5l3 3M16 16l3 3M5 19l3-3M16 8l3-3"/>'};
 return `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||''}</svg>`;
}
function home(){
 const mastered=questions.filter(q=>(saved.questions[q.id]?.streak||0)>=2).length;
 const studied=Object.values(saved.chapters).filter(Boolean).length;
 const cleanDrills=drills.filter(d=>saved.drills[d.id]?.clean).length;
 const readyManuals=Object.keys(manuals).filter(id=>privateManuals.status(id).ready).length;
 const last=Object.hasOwn(studyAreas,saved.lastSection)?saved.lastSection:null;
 $('workspace').innerHTML=`<div class="study-home">
  <header class="desk-heading"><div><span class="eyebrow">Qantas · A321P2F</span><h1>Your study desk</h1><p>Pick a topic. Practise at your own pace.</p></div>${last?`<a class="desk-continue" href="#${last}"><span>Last opened</span><strong>${studyAreas[last]} <span aria-hidden="true">→</span></strong></a>`:''}</header>
  <section aria-labelledby="studyChoicesTitle"><div class="desk-section-heading"><h2 id="studyChoicesTitle">What would you like to work on?</h2><span>One aircraft. All your study in one place.</span></div>
   <div class="study-choices">
    <article class="study-choice"><span class="desk-icon">${deskIcon('flow')}</span><h3>Flows</h3><p>Learn the panel scan, then practise the sequence.</p><span class="choice-detail">11 flow patterns · 8 recall drills</span><div class="choice-actions"><a class="button" href="#flows">Practise flows <span aria-hidden="true">→</span></a></div></article>
    <article class="study-choice"><span class="desk-icon">${deskIcon('procedure')}</span><h3>Procedures</h3><p>Work through the procedure and its source guidance.</p><span class="choice-detail">Normal operations · Abnormal scenarios</span><div class="choice-actions procedure-actions"><a class="button" href="#normal">Normal procedures</a><a class="desk-text-link" href="#abnormal">Abnormal procedures <span aria-hidden="true">→</span></a></div></article>
    <article class="study-choice practice-choice"><span class="desk-icon">${deskIcon('limits')}</span><h3>Limitations</h3><p>Build your recall, with an explanation after each answer.</p><span class="choice-detail">92 questions · Learn, exam & flashcards</span><div class="choice-actions"><a class="button primary" href="#limitations/quick">Practise 10 questions <span aria-hidden="true">→</span></a><a class="desk-text-link" href="#limitations">All practice options</a></div></article>
   </div>
  </section>
  <section class="desk-resources" aria-labelledby="deskResourcesTitle"><div class="desk-section-heading"><h2 id="deskResourcesTitle">Read & explore</h2></div><div class="resource-grid">
   <div class="manual-resource"><div class="resource-title"><span class="desk-icon small">${deskIcon('book')}</span><h3>Your manuals</h3></div><p>${readyManuals===0?'Load your PDFs to see the original flow diagrams and procedure pages.':readyManuals===3?'Your three manuals are ready. Browse pages or search for a topic.':'Load the remaining PDFs to open all source pages.'}</p><div class="manual-pills">${Object.keys(manuals).map(id=>{const ready=privateManuals.status(id).ready;return `<span class="manual-pill${ready?' ready':''}"><strong>${id}</strong><span>${ready?'Ready':'Not loaded'}</span></span>`;}).join('')}</div><div class="resource-bottom"><a class="desk-text-link" href="#manuals">${readyManuals===0?'Load your manuals':'Open manual library'} <span aria-hidden="true">→</span></a><small>Private on this device</small></div></div>
   <a class="systems-resource" href="#systems"><div class="resource-title"><span class="desk-icon small">${deskIcon('systems')}</span><h3>Aircraft systems</h3></div><p>Connect the procedures with how the aircraft works.</p><span class="systems-topics">Engines · Electrical · Hydraulics · Freighter systems</span><span class="desk-text-link">Explore systems <span aria-hidden="true">→</span></span></a>
  </div></section>
  <section class="desk-progress" aria-labelledby="deskProgressTitle"><div class="desk-section-heading"><h2 id="deskProgressTitle">Your progress</h2><span>Saved on this device</span></div><div class="desk-progress-grid">
   <div class="progress-item"><div><h3>Limitations recalled</h3><strong>${mastered}<span> / ${questions.length}</span></strong></div><progress value="${mastered}" max="${questions.length}" aria-label="Limitations recalled twice correctly"></progress><p>Correct on two consecutive attempts</p></div>
   <div class="progress-item"><div><h3>Flow drills completed</h3><strong>${cleanDrills}<span> / ${drills.length}</span></strong></div><progress value="${cleanDrills}" max="${drills.length}" aria-label="Flow drills completed without help or a miss"></progress><p>Without a miss or an answer reveal</p></div>
   <div class="progress-item"><div><h3>Sections studied</h3><strong>${studied}</strong></div><p class="study-count-note">Sections you have marked as read</p></div>
  </div><details class="progress-settings"><summary>Manage progress</summary><p>Reset question results, flow results and read marks. Your private manuals stay on this device.</p><button id="resetProgress">Reset study progress</button></details></section>
 </div>`;
 $('resetProgress').onclick=()=>{if(confirm('Reset Qantas A321P2F study progress on this device? Your private manuals will be kept.')){saved={questions:{},chapters:{},drills:{}};persist();home();}};
}

function flows(){
 $('workspace').innerHTML=header('FCOM · Normal procedures','Flow patterns','Study the original patterns or practise selected actions. Crew roles stay as printed; PF/PM and CM1/CM2 are not interchangeable.')+`<div class="tabs"><button id="patternsTab" aria-pressed="true">11 original patterns</button><button id="drillsTab" aria-pressed="false">8 sequence drills</button></div><div class="split"><aside class="listbox" id="flowList" aria-label="Flow selection"></aside><section id="flowDetail" class="panel"></section></div>`;
 $('patternsTab').onclick=()=>showFlowList('patterns');$('drillsTab').onclick=()=>showFlowList('drills');showFlowList('patterns');
}
function showFlowList(kind){flowRun=null;for(const k of ['patterns','drills'])$(k+'Tab').setAttribute('aria-pressed',String(k===kind));const items=kind==='patterns'?patterns:drills;
 $('flowList').innerHTML=items.map((d,i)=>`<button data-index="${i}" class="${i===0?'active':''}">${esc(d.title)}</button>`).join('');
 $('flowList').onclick=e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('#flowList button').forEach(x=>x.classList.toggle('active',x===b));kind==='patterns'?showPattern(items[+b.dataset.index]):showDrill(items[+b.dataset.index]);};kind==='patterns'?showPattern(items[0]):showDrill(items[0]);
}
function localLoader(doc){return `<div class="local-loader"><p>Choose your <strong>${doc}</strong> PDF to read its original pages. The file stays on this device.</p><label class="file-label">Load ${doc} PDF<input type="file" accept="application/pdf,.pdf" data-import="${doc}"></label><label class="remember"><input type="checkbox" data-remember checked> Keep privately in this browser for next time</label><p class="import-status hint" role="status"></p></div>`;}
async function renderPrivatePage(doc,page,node){if(!node)return;if(!privateManuals.status(doc).ready){node.innerHTML=localLoader(doc);return;}node.innerHTML='<p class="loading">Opening your local PDF page…</p>';try{await privateManuals.render(doc,page,node);}catch(err){if(node.isConnected)node.innerHTML='<p class="error">'+esc(err.message)+'</p>';}}
function showPattern(d){flowRun=null;$('flowDetail').innerHTML=`<span class="tag">Original FCOM page · private</span><h2>${esc(d.title)}</h2><p class="hint">Use the printed arrows, crew-role colours and step labels. Open the source for full-size viewing and surrounding procedure conditions.</p>${pageButton('FCOM',d.page,'Open source procedure')}<div class="pattern-frame" data-render-doc="FCOM" data-render-page="${d.page}"></div>`;renderPrivatePage('FCOM',d.page,$('flowDetail').querySelector('.pattern-frame'));}
function showDrill(d){flowRun=null;$('flowDetail').innerHTML=`<span class="tag">Selected actions · source order</span><h2>${esc(d.title)}</h2><p>${esc(d.scope)}</p><div class="actions"><button id="beginRecall" class="primary">Practise recall</button></div><ol class="step-list">${d.steps.map((s,i)=>`<li><span class="step-index">${i+1}</span><div><strong>${esc(s.label)}</strong> <span class="tag">${esc(s.role)}</span><p>${esc(s.target)}</p></div>${(s.pages||[s.page]).map(p=>pageButton('FCOM',p)).join(' ')}</li>`).join('')}</ol>${d.pattern?`<details class="diagram-disclosure"><summary>View the printed pattern</summary><div class="pattern-frame" data-render-doc="FCOM" data-render-page="${d.pattern}"></div></details>`:''}`;$('beginRecall').onclick=()=>beginFlowRecall(d);const disclosure=$('flowDetail').querySelector('details');if(disclosure)disclosure.ontoggle=()=>{if(disclosure.open)renderPrivatePage('FCOM',d.pattern,disclosure.querySelector('.pattern-frame'));};}
function beginFlowRecall(d){flowRun={drill:d,index:0,misses:0,selected:new Set(),revealed:false};$('flowDetail').innerHTML=`<span class="tag">Recall mode</span><h2>${esc(d.title)}</h2><p>${esc(d.scope)}</p><p class="hint">Select the next action in this drill’s printed source order. These are study selections, not cockpit switch simulation.</p><div class="quiz-progress"><progress id="flowProgress" max="${d.steps.length}" value="0"></progress><span id="flowCount">0 / ${d.steps.length}</span></div><div class="recall-grid" id="flowChoices">${shuffle(d.steps.map((s,i)=>({s,i}))).map(({s,i})=>`<button data-step="${i}">${esc(s.label)} <span class="tag">${esc(s.role)}</span></button>`).join('')}</div><div class="status" id="flowFeedback" role="status">Choose the first action.</div><div class="actions" style="margin-top:18px"><button id="showFlowAnswer">Show next action</button><button id="stopFlow">Back to guided study</button></div>`;
 $('flowChoices').onclick=e=>{const b=e.target.closest('button');if(!b||b.disabled||!flowRun)return;const i=+b.dataset.step,r=flowRun;if(i!==r.index){r.misses++;$('flowFeedback').className='status wrong';$('flowFeedback').textContent='That action comes later. Think through the source order and try again.';return;}const s=d.steps[i];b.disabled=true;b.classList.add('done');b.prepend(document.createTextNode((i+1)+'. '));r.index++;$('flowProgress').value=r.index;$('flowCount').textContent=r.index+' / '+d.steps.length;$('flowFeedback').className='status correct';$('flowFeedback').innerHTML=`<strong>${esc(s.label)}</strong>: ${esc(s.target)} <div>${(s.pages||[s.page]).map(p=>pageButton('FCOM',p)).join(' ')}</div>`;if(r.index===d.steps.length){const clean=r.misses===0&&!r.revealed;saved.drills[d.id]={clean,misses:r.misses,date:new Date().toISOString()};persist();$('showFlowAnswer').disabled=true;$('flowFeedback').innerHTML+=`<p><strong>Drill complete.</strong> ${clean?'Completed without help or a miss.':'Review and repeat for an unassisted recall.'}</p>`;}};
 $('showFlowAnswer').onclick=()=>{const r=flowRun;r.revealed=true;$('flowFeedback').className='status';$('flowFeedback').textContent='Next: '+d.steps[r.index].label+' — '+d.steps[r.index].target;};$('stopFlow').onclick=()=>showDrill(d);
}
function normal(){
 $('workspace').innerHTML=header('FCOM · FCTM · QRH','Normal procedures','Read the SOP, connect it with the technique, and mark each section when you have studied it. Equipment-specific branches stay within the relevant procedure.',pageButton('QRH',329,'Normal checklist'))+`<div class="filters"><label>Find a procedure<input id="chapterSearch" type="search" placeholder="Cockpit preparation, approach, securing…"></label><label>Chapter group<select id="normalGroup"><option value="sop">Standard operating procedures</option><option value="supp">Supplementary procedures</option><option value="system">Systems-related procedures</option><option value="checklist">FCTM normal checklists</option><option value="qrh">QRH normal procedures</option></select></label></div><div id="chapterList" class="catalog"></div>`;
 const render=()=>{const group=$('normalGroup').value;let doc='FCOM',items=chapters('FCOM',3615,3808,4);if(group==='supp')items=chapters('FCOM',3849,3932,4);if(group==='system')items=chapters('FCOM',3933,4050,4);if(group==='checklist'){doc='FCTM';items=chapters('FCTM',347,354,4);}if(group==='qrh'){doc='QRH';items=chapters('QRH',261,264,2);}renderCatalog(items,doc,$('chapterSearch').value);};$('chapterSearch').oninput=render;$('normalGroup').onchange=render;render();
}
function renderCatalog(items,doc,term=''){
 const q=term.toLowerCase().trim();items=items.filter(x=>(x.title+' '+x.path).toLowerCase().includes(q));
 $('chapterList').innerHTML=items.length?items.map(x=>{const id=doc+'-'+x.page+'-'+x.title;const technique=doc==='FCOM'?manuals.FCTM.outline.find(t=>t.level===4&&t.page>=209&&t.page<=345&&t.title.toLowerCase()===x.title.toLowerCase()):null;return `<article class="catalog-row"><div class="row-main"><h3>${esc(x.title)}</h3><p>${doc} · PDF pp. ${x.page}–${x.end}</p>${technique?`<div class="source-row">${pageButton('FCTM',technique.page,'FCTM technique')}</div>`:''}<span class="read-mark">${saved.chapters[id]?'Marked studied':''}</span></div><div class="actions">${pageButton(doc,x.page,'Read '+doc)}<button data-studied="${esc(id)}">${saved.chapters[id]?'Mark unread':'Mark studied'}</button></div></article>`;}).join(''):'<div class="panel">No matching sections. Try a broader search.</div>';
}
function systems(){
 $('workspace').innerHTML=header('FCOM · Aircraft systems','Understand the systems','Descriptions, controls, indications and operation from the supplied freighter manual.')+`<div class="filters"><label>Find a system<input id="chapterSearch" type="search" placeholder="Electrical, hydraulic, engines, main deck…"></label></div><div class="actions" style="margin-bottom:22px"><a class="button" href="engine.html">Engine explorer</a><a class="button" href="electrical.html">Electrical explorer</a><a class="button" href="hydraulic.html">Hydraulic explorer</a><a class="button" href="integration.html">Cross-system scenarios</a></div><div id="chapterList" class="catalog"></div>`;const render=()=>renderCatalog(chapters('FCOM',205,2494,2),'FCOM',$('chapterSearch').value);$('chapterSearch').oninput=render;render();
}
const scenarios=[
 ['Main deck smoke','Recognition, the freighter procedure and coordination with supernumeraries.',[['FCOM',3507],['QRH',251],['FCTM',524,'FCTM · Crew coordination']]],
 ['Unreliable speed','Recall the recognition cues and initial priorities, then check the source conditions.',[['FCOM',3377],['QRH',229],['FCTM',495],['FCTM',497]]],
 ['All engines fail','Study the QRH branches and restart considerations in the exact source.',[['QRH',161],['FCTM',407]]],
 ['Electrical emergency configuration','Study the procedure, remaining systems and handling technique.',[['FCOM',2907],['FCOM',2830,'FCOM · Systems remaining'],['QRH',153],['FCTM',405]]],
 ['Hydraulic system losses','Compare all three combinations. Equipment and procedure variants are noted within each FCOM section; follow the applicable branch.',[['FCOM',3261,'FCOM · B+Y'],['FCOM',3273,'FCOM · G+B'],['FCOM',3285,'FCOM · G+Y'],['QRH',197,'QRH · B+Y'],['QRH',198,'QRH · G+B'],['QRH',200,'QRH · G+Y'],['FCTM',447]]],
 ['Smoke, fumes or avionics smoke','Study source identification, procedure branches and smoke removal.',[['FCOM',3495],['QRH',243],['FCTM',523]]],
 ['Emergency descent','Review the published procedure and the relevant crew priorities.',[['QRH',212],['FCTM',461]]],
 ['Abnormal-operation method','Study tasksharing, control handling and ECAM/QRH/OEB use.',[['FCOM',2557],['FCTM',93],['FCTM',97]]]
];
function abnormal(){
 $('workspace').innerHTML=header('FCOM · QRH · FCTM','Abnormal procedures','Study the published procedure together with its handling technique. Recall prompts are self-assessed; the original source supplies the actions.')+`<div class="tabs"><button id="scenariosTab" aria-pressed="true">Scenario study</button><button id="abnormalIndexTab" aria-pressed="false">Complete procedure index</button><button data-source="FCOM" data-page="2577">Memory-item index</button><button data-source="QRH" data-page="327">QRH back cover</button></div><div id="abnormalBody"></div>`;
 $('scenariosTab').onclick=()=>showScenarios();$('abnormalIndexTab').onclick=()=>showAbnormalIndex();showScenarios();
}
function showScenarios(){$('scenariosTab').setAttribute('aria-pressed','true');$('abnormalIndexTab').setAttribute('aria-pressed','false');$('abnormalBody').innerHTML=`<div class="grid two">${scenarios.map(([title,desc,refs],i)=>`<article class="panel"><span class="eyebrow">Study scenario ${String(i+1).padStart(2,'0')}</span><h2>${esc(title)}</h2><p class="muted">${esc(desc)}</p><details><summary>Recall, then review the sources</summary><p style="margin-top:15px">Describe the recognition cues, immediate priorities, PF/PM tasksharing, relevant procedure branches and follow-up considerations. Compare your recall against the full applicable source pages.</p><div class="source-row">${refs.map(([d,p,label])=>pageButton(d,p,label)).join('')}</div></details></article>`).join('')}</div>`;}
function showAbnormalIndex(){$('scenariosTab').setAttribute('aria-pressed','false');$('abnormalIndexTab').setAttribute('aria-pressed','true');$('abnormalBody').innerHTML=`<div class="filters"><label>Find an abnormal procedure<input id="abSearch" type="search" placeholder="Engine fire, smoke, fuel leak, reset…"></label><label>Manual<select id="abDoc"><option>FCOM</option><option>QRH</option><option>FCTM</option></select></label></div><div id="chapterList" class="catalog"></div>`;const render=()=>{const doc=$('abDoc').value;const [start,end,level]=doc==='FCOM'?[2557,3596,4]:doc==='QRH'?[49,256,3]:[395,532,4];renderCatalog(chapters(doc,start,end,level),doc,$('abSearch').value);};$('abSearch').oninput=render;$('abDoc').onchange=render;render();}
function limitations(){activeRun=null;const pool=questions,categories=[...new Set(pool.map(q=>q.category))];
 $('workspace').innerHTML=header('FCOM · Limitations','Know your A321P2F limits',`${pool.length} A321P2F questions. Every answer links to the supplied manual; variant notes appear beside the relevant question.`)+`<div class="desk"><section class="panel"><h2>Test your recall</h2><div class="filters"><label>Subject<select id="quizSubject"><option value="ALL">All subjects</option>${categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select></label><label>Mode<select id="quizMode"><option value="learn">Learn — immediate feedback</option><option value="exam">Exam — feedback at the end</option><option value="flash">Flashcards — self-assessment</option></select></label><label>Questions<select id="quizLength"><option value="10">Quick 10</option><option value="25">25 questions</option><option value="0">All questions</option></select></label></div><div class="actions"><button class="primary" id="startQuiz">Begin practice</button><button id="weakQuiz">Review weak questions</button></div><p class="hint" id="poolCount" style="margin-top:16px"></p><p class="hint">Scored mastery requires two consecutive correct recalls. Flashcard self-assessment does not award scored mastery. Exams show answers only when complete.</p></section><section class="panel"><h2>Read the complete limitations</h2><p class="muted">The quiz is a selected study set. All limitations, charts, conditions and registration variants remain available in the original manual.</p><div class="actions">${pageButton('FCOM',4093,'Open limitations chapter')}${pageButton('FCOM',4187,'Freighter limitations')}${pageButton('FCOM',35,'Aircraft allocation')}</div><p class="notice">The supplied aircraft pages contain different ventilation tables and equipment options. Always check the printed applicability.</p><a href="#manuals">Search all source pages</a></section></div><section style="margin-top:28px"><h2>Browse by limitation subject</h2><div class="grid">${chapters('FCOM',4105,4242,2).map(c=>`<article class="panel"><h3>${esc(c.title)}</h3>${pageButton('FCOM',c.page,'Read chapter')}</article>`).join('')}</div></section>`;
 const count=()=>{const p=pool.filter(q=>$('quizSubject').value==='ALL'||q.category===$('quizSubject').value);$('poolCount').textContent=p.length+' questions · '+p.filter(q=>saved.questions[q.id]?.weak).length+' marked weak';};$('quizSubject').onchange=count;count();
 $('startQuiz').onclick=()=>startQuiz(false);$('weakQuiz').onclick=()=>startQuiz(true);
}
function startQuiz(weak){const subject=$('quizSubject').value,mode=$('quizMode').value,length=+$('quizLength').value;let pool=questions.filter(q=>subject==='ALL'||q.category===subject);if(weak)pool=pool.filter(q=>saved.questions[q.id]?.weak);if(!pool.length){toast('There are no weak questions in this selection yet.');return;}pool=shuffle(pool);if(mode==='learn')pool.sort((a,b)=>(saved.questions[a.id]?.streak||0)-(saved.questions[b.id]?.streak||0));if(length)pool=pool.slice(0,length);activeRun={pool,mode,index:0,answers:[],revealed:false};renderQuestion();}
function renderQuestion(){const r=activeRun,q=r.pool[r.index];r.revealed=false;$('workspace').innerHTML=`<div class="questions">${header(q.category,r.mode==='flash'?'Recall the limitation':'Limitations practice',`A321P2F · ${r.mode==='exam'?'Exam: answers shown at the end':r.mode==='flash'?'Self-assessment':'Learn: immediate feedback'}`)}<section class="panel"><div class="quiz-progress"><progress max="${r.pool.length}" value="${r.index}"></progress><span>${r.index+1} / ${r.pool.length}</span></div><h2 id="questionTitle" class="question-title" tabindex="-1">${esc(q.question)}</h2>${q.applicability[0]!=='ALL'?`<p class="notice variant-note"><strong>Variant note:</strong> This ventilation table applies to ${esc(q.applicability.join(', '))}. ${pageButton(q.manual,q.pages[0],'Compare source tables')}</p>`:''}<div id="answerArea">${r.mode==='flash'?'<button id="revealFlash" class="primary">Reveal answer</button>':`<div class="answers">${shuffle(q.options.map((text,index)=>({text,index}))).map(({text,index},i)=>`<button class="answer" data-answer="${index}"><span class="answer-label">${String.fromCharCode(65+i)}</span><span>${esc(text)}</span></button>`).join('')}</div>`}</div><div id="quizFeedback" role="status"></div><div class="actions" style="margin-top:20px"><button class="primary" id="nextQuestion" hidden>${r.index===r.pool.length-1?'View results':'Next question'}</button><button id="exitQuiz">End practice</button></div></section></div>`;
 $('questionTitle').focus();if(r.mode==='flash')$('revealFlash').onclick=()=>revealFlash(q);else $('answerArea').onclick=e=>{const b=e.target.closest('[data-answer]');if(!b||b.disabled)return;chooseAnswer(+b.dataset.answer);};$('nextQuestion').onclick=()=>{if(r.answers.length!==r.index+1)return;r.index++;if(r.index===r.pool.length)finishQuiz();else renderQuestion();};$('exitQuiz').onclick=()=>{if(confirm('End this practice run? An incomplete exam will not be scored or update mastery.')){if(r.mode==='exam')activeRun=null;limitations();}};
}
function recordQuestion(q,correct){const old=saved.questions[q.id]||{};saved.questions[q.id]={streak:correct?(old.streak||0)+1:0,weak:!correct,seen:(old.seen||0)+1};}
function chooseAnswer(index){const r=activeRun;if(!r||r.answers.length>r.index)return;const q=r.pool[r.index],correct=index===q.answer;r.answers.push(index);document.querySelectorAll('.answer').forEach(b=>{b.disabled=true;if(+b.dataset.answer===index)b.classList.add('chosen');if(r.mode==='learn'){if(+b.dataset.answer===q.answer)b.classList.add('correct');if(+b.dataset.answer===index&&!correct)b.classList.add('incorrect');}});if(r.mode==='learn'){recordQuestion(q,correct);persist();$('quizFeedback').innerHTML=`<div class="feedback"><strong>${correct?'Correct.':'Review this limitation.'}</strong><p>Correct answer: ${esc(q.options[q.answer])}</p><p>${esc(q.explanation)}</p>${sourceButtons(q)}</div>`;}else $('quizFeedback').textContent='Answer recorded. Review follows the completed exam.';$('nextQuestion').hidden=false;$('nextQuestion').focus();}
function revealFlash(q){const r=activeRun;r.revealed=true;$('answerArea').innerHTML=`<div class="flash-answer">${esc(q.options[q.answer])}</div><p>${esc(q.explanation)}</p>${sourceButtons(q)}<div class="actions"><button id="flashAgain">Needs more practice</button><button id="flashKnown">Recalled it</button></div>`;const rate=known=>{if(r.answers.length>r.index)return;r.answers.push(known);if(!known){saved.questions[q.id]={...(saved.questions[q.id]||{}),weak:true};persist();}for(const id of ['flashAgain','flashKnown'])$(id).disabled=true;$('nextQuestion').hidden=false;$('nextQuestion').focus();};$('flashAgain').onclick=()=>rate(false);$('flashKnown').onclick=()=>rate(true);}
function finishQuiz(){const r=activeRun;if(!r||r.answers.length!==r.pool.length)return;const flash=r.mode==='flash',correct=r.answers.filter((a,i)=>flash?a:a===r.pool[i].answer).length;if(r.mode==='exam'){r.pool.forEach((q,i)=>recordQuestion(q,r.answers[i]===q.answer));persist();}const percent=correct/r.pool.length*100;const review=r.pool.map((q,i)=>`<article class="review-row"><span class="tag">${flash?(r.answers[i]?'Self-rated recalled':'Needs practice'):(r.answers[i]===q.answer?'Correct':'Needs practice')}</span><h3>${esc(q.question)}</h3>${!flash?`<p>Your answer: ${esc(q.options[r.answers[i]])}</p>`:''}<p><strong>Answer: ${esc(q.options[q.answer])}</strong></p><p>${esc(q.explanation)}</p>${sourceButtons(q)}</article>`).join('');$('workspace').innerHTML=`<div class="questions">${header('Completed practice',flash?'Flashcard review':'Your results',flash?'Self-assessment is recorded separately from scored mastery.':'Review the source pages for any gaps. This is a study result, not an operational qualification.')}<section class="panel"><div class="result-score">${correct} / ${r.pool.length}</div><p>${flash?'Recalled by self-assessment':percent.toFixed(1)+'% · '+(correct*100>=r.pool.length*80?'Study target reached (80%)':'Keep practising toward the 80% study target')}</p><div class="actions"><button id="againQuiz" class="primary">Choose another practice</button><a class="button" href="#home">Study desk</a></div><details style="margin-top:24px" open><summary>Review answers and sources</summary>${review}</details></section></div>`;$('againQuiz').onclick=limitations;activeRun=null;}
function library(){
 $('workspace').innerHTML=header('Private source library','FCOM · FCTM · QRH','Load the supplied PDFs from your device. They are read and searched here in your browser; nothing is uploaded.')+`<div class="grid">${Object.values(manuals).map(m=>`<section class="panel manual-card"><span class="manual-name">${m.id}</span><h3>${esc(m.title)}</h3><p class="hint">${m.pages.toLocaleString()} pages · Effective ${m.revision}<br>${(m.size/1e6).toFixed(1)} MB · A321P2F</p><p class="local-status tag" data-status="${m.id}"></p>${localLoader(m.id)}<div class="actions">${pageButton(m.id,1,'Read manual')}<button data-forget="${m.id}">Remove local copy</button></div></section>`).join('')}</div><div class="notice">Loading a manual unlocks its original flow diagrams, page viewer and full-text search. “Keep privately” stores the file only in this browser. You can remove it at any time; clearing browser data also removes it. Study links use the supplied editions listed above, checked when you load them.</div><section class="panel"><h2>Find a section or phrase</h2><div class="filters"><label>Search<input id="manualSearch" type="search" placeholder="Main deck cargo door, engine oil, unreliable speed…"></label><label>Manual<select id="searchDoc"><option value="ALL">All three manuals</option><option>FCOM</option><option>FCTM</option><option>QRH</option></select></label><label>Search in<select id="searchType"><option value="sections">Section titles</option><option value="pages">Full page text · loaded PDFs</option></select></label><button id="runSearch" class="primary">Search</button></div><p id="searchStatus" class="hint" role="status"></p><div id="searchResults"></div><button id="moreResults" hidden>Show more results</button></section><details class="panel" style="margin-top:20px"><summary>Source versions and integrity</summary><p class="manual-note">The PDFs retain all original wording, revision details and effectivity. Text search is a finding aid; use the original page for tables, symbols and conditions. These supplied versions are not a claim that no later revision exists.</p>${Object.values(manuals).map(m=>`<p class="hint"><strong>${m.id}</strong><br><code style="overflow-wrap:anywhere">${m.sha256}</code></p>`).join('')}</details>`;
 $('runSearch').onclick=runSearch;$('manualSearch').onkeydown=e=>{if(e.key==='Enter')runSearch();};$('searchDoc').onchange=runSearch;$('searchType').onchange=runSearch;refreshLocalStatus();runSearch();
}
function refreshLocalStatus(){document.querySelectorAll('[data-status]').forEach(node=>{const s=privateManuals.status(node.dataset.status);node.textContent=s.ready?(s.remembered?'Saved privately on this device':'Loaded for this visit'):'Choose your local PDF';});document.querySelectorAll('[data-forget]').forEach(b=>b.disabled=!privateManuals.status(b.dataset.forget).ready);}
async function runSearch(){const gen=++searchGeneration,term=$('manualSearch').value.trim().toLowerCase().replace(/\s+/g,' '),doc=$('searchDoc').value,type=$('searchType').value;const docs=doc==='ALL'?Object.keys(manuals):[doc];$('searchStatus').textContent=type==='pages'?'Preparing local page search…':'Searching sections…';$('searchResults').innerHTML='';$('moreResults').hidden=true;try{let hits=[],missing=[];if(type==='pages'){if(term.length<2){$('searchStatus').textContent='Enter at least two characters to search page text.';return;}for(const d of docs){if(!privateManuals.status(d).ready){missing.push(d);continue;}const pages=await privateManuals.pages(d,(n,total)=>{if(gen===searchGeneration&&$('searchStatus'))$('searchStatus').textContent=`Reading ${d} locally: ${n.toLocaleString()} / ${total.toLocaleString()} pages… First search prepares the index for this visit.`;},()=>gen!==searchGeneration);for(const p of pages){const searchable=p.text.replace(/\s+/g,' '),at=searchable.toLowerCase().indexOf(term);if(at>=0)hits.push({doc:d,page:p.page,title:d+' · PDF page '+p.page,snippet:searchable.slice(Math.max(0,at-100),at+400)});}}}else for(const d of docs)for(const x of manuals[d].outline)if(x.level>1&&!/Preliminary Pages|Table of Contents|Summary of Highlights|List of Effective/.test(x.title)&&(!term||(x.title+' '+x.path).toLowerCase().includes(term)))hits.push({doc:d,page:x.page,title:x.title,snippet:x.path});if(gen!==searchGeneration||!$('searchResults'))return;let count=0;$('searchStatus').textContent=hits.length+' matches'+(type==='pages'?' · Searched on this device.':'')+(missing.length?' Load '+missing.join(', ')+' above to include '+(missing.length===1?'it.':'them.'):'');const more=()=>{const slice=hits.slice(count,count+40);$('searchResults').insertAdjacentHTML('beforeend',slice.map(h=>`<article class="search-hit"><h3>${esc(h.title)}</h3><p>${esc(h.snippet)}</p>${pageButton(h.doc,h.page)}</article>`).join(''));count+=slice.length;$('moreResults').hidden=count>=hits.length;};$('moreResults').onclick=more;more();if(!hits.length)$('searchResults').innerHTML='<p>'+(missing.length?'Load your manuals above, then search again.':'No matches. Try another phrase or search the full page text.')+'</p>';}catch(err){if(gen===searchGeneration&&$('searchStatus'))$('searchStatus').textContent=err.message;}}
async function openReader(doc,page){if(!manuals[doc])return;page=Math.max(1,Math.min(manuals[doc].pages,Math.floor(Number(page))||1));readerState={doc,page,text:false};if(!$('reader').open)$('reader').showModal();renderReader();}
async function renderReader(){const r=readerState,gen=++readerGeneration;if(!r)return;const m=manuals[r.doc];$('readerTitle').textContent='A321P2F '+r.doc;$('readerMeta').textContent=m.title+' · Effective '+m.revision;$('pageNumber').value=r.page;$('pageNumber').max=m.pages;$('prevPage').disabled=r.page<=1;$('nextPage').disabled=r.page>=m.pages;$('textMode').textContent=r.text?'Show original PDF':'Show searchable text';const ready=privateManuals.status(r.doc).ready;$('openPdf').hidden=!ready;$('textMode').disabled=!ready;const body=$('readerBody');if(!ready){$('openPdf').removeAttribute('href');body.innerHTML=localLoader(r.doc);return;}$('openPdf').href=privateManuals.originalURL(r.doc)+'#page='+r.page;body.innerHTML='<div class="pdf-page"><p class="loading">Opening your local source page…</p></div>';const container=body.firstElementChild;try{if(!r.text){await privateManuals.render(r.doc,r.page,container);}else{const text=await privateManuals.pageText(r.doc,r.page);if(gen!==readerGeneration)return;const pre=document.createElement('pre');pre.textContent=text||'No extractable text on this page. Use original PDF view for the diagram.';body.replaceChildren(pre);}}catch(err){if(gen===readerGeneration)body.innerHTML='<p class="error">'+esc(err.message)+'</p>';}}
function route(){activeRun=null;flowRun=null;searchGeneration++;if($('reader').open)$('reader').close();const parts=location.hash.slice(1).split('/'),key=parts[0]||'home';if(key==='source'&&manuals[parts[1]]){library();openReader(parts[1],+parts[2]||1);return;}document.querySelectorAll('.main-nav a').forEach(a=>a.setAttribute('aria-current',a.hash==='#'+key?'page':'false'));if(Object.hasOwn(studyAreas,key)){saved.lastSection=key;persist();}({home,flows,normal,abnormal,limitations,manuals:library,systems}[key]||home)();if(key==='limitations'&&parts[1]==='quick'){$('quizLength').value='10';startQuiz(false);}window.scrollTo(0,0);}
document.addEventListener('click',e=>{const src=e.target.closest('[data-source]');if(src){openReader(src.dataset.source,+src.dataset.page);return;}const study=e.target.closest('[data-studied]');if(study){const id=study.dataset.studied;saved.chapters[id]=!saved.chapters[id];persist();study.textContent=saved.chapters[id]?'Mark unread':'Mark studied';study.closest('.catalog-row').querySelector('.read-mark').textContent=saved.chapters[id]?'Marked studied':'';}});
function clearClosedReader(){if($('reader').open)return;readerGeneration++;readerState=null;$('readerBody').replaceChildren();$('openPdf').removeAttribute('href');}
$('closeReader').onclick=()=>{$('reader').close();clearClosedReader();};$('prevPage').onclick=()=>{readerState.page--;renderReader();};$('nextPage').onclick=()=>{readerState.page++;renderReader();};const goPage=()=>{readerState.page=Math.max(1,Math.min(manuals[readerState.doc].pages,Math.floor(+$('pageNumber').value)||1));renderReader();};$('goPage').onclick=goPage;$('pageNumber').onkeydown=e=>{if(e.key==='Enter')goPage();};$('textMode').onclick=()=>{readerState.text=!readerState.text;renderReader();};
document.addEventListener('change',async e=>{const input=e.target.closest('[data-import]');if(!input||!input.files[0])return;const box=input.closest('.local-loader'),status=box.querySelector('.import-status');input.disabled=true;status.textContent='Checking the local PDF edition…';try{const message=await privateManuals.load(input.dataset.import,input.files[0],box.querySelector('[data-remember]').checked);status.textContent=message;toast(message);if($('reader').open)renderReader();document.querySelectorAll('[data-render-doc]').forEach(node=>renderPrivatePage(node.dataset.renderDoc,+node.dataset.renderPage,node));}catch(err){status.textContent=err.message;}finally{input.disabled=false;input.value='';refreshLocalStatus();}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-forget]');if(!b)return;searchGeneration++;b.disabled=true;try{await privateManuals.forget(b.dataset.forget);if($('searchResults'))$('searchResults').innerHTML='';if($('searchStatus'))$('searchStatus').textContent='Local copy removed. Your original file is unchanged.';toast(b.dataset.forget+' removed from this browser.');}catch(err){if($('searchStatus'))$('searchStatus').textContent=err.message;toast(err.message);}finally{refreshLocalStatus();}});
window.addEventListener('manuals-changed',()=>{if(privateManuals)refreshLocalStatus();});
$('reader').addEventListener('close',clearClosedReader);
Promise.all(['manuals','questions','patterns','drills'].map(f=>loadJson('data/'+f+'.json'))).then(async ([m,q,p,d])=>{privateManuals=await import('./private-manuals.mjs');await privateManuals.init(m);manuals=m;questions=q;patterns=p;drills=d;if(Object.hasOwn(saved,'aircraft')){delete saved.aircraft;persist();}window.addEventListener('hashchange',route);route();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').then(reg=>reg.update()).catch(()=>{}); }).catch(err=>{$('workspace').innerHTML='<div class="error"><h1>Study files could not load</h1><p>Connect and reload using a current version of Chrome, Edge, Firefox or Safari. Your PDFs remain on your device.</p><button onclick="location.reload()">Reload trainer</button></div>';});
