(function(root){
  'use strict';
  const source={
    title:'CASR Division 61.L.5 — Pilot type ratings',
    compilation:'102 · 30 June 2026 · F2026C00560',
    checked:'2026-10-04',
    url:'https://www.legislation.gov.au/F1998B00220/2026-06-30/2026-06-30/text/original/pdf/2',
    amendmentUrl:'https://www.legislation.gov.au/F2026L00846/asmade/2026-06-29/text/original/pdf',
    amendmentCheck:'F2026L00846: Schedule 1 commenced 30 June 2026; Schedules 2 and 3 commenced 29 September 2026 and do not change 61.770–61.805.',
    reviewCreditFrom:'2026-06-30',
    currentUrl:'https://www.legislation.gov.au/F1998B00220/latest/text',
    handout:'assets/type-ratings/casr-handout.jpeg',
    handoutSha256:'a9abdb331d13f10928eada5c0b8e08e9999262f800da118ac280a7416ff44955'
  };
  const questions=[
    {id:'TR01',ref:'61.770',q:'What does a pilot type rating authorise its holder to do?',o:['Exercise existing licence privileges in the aircraft type, subject to the applicable limitations','Exercise commercial privileges in the aircraft type regardless of the licence held','Exercise licence privileges in any aircraft with the same engine category','Exercise PIC privileges in the type without further recency requirements'],a:0,w:'The rating applies the privileges of the licence to the aircraft type. Subpart 61.E and regulations 61.775–61.805 still apply.'},
    {id:'TR02',ref:'61.775(1)',q:'When does the simulator-flight-test experience restriction in 61.775 apply?',o:['Whenever a type-rating course includes simulator training','When a multi-engine turbine aircraft type-rating flight test was passed in a flight simulator','When an aircraft flight test follows simulator training','Only when an instrument proficiency check is completed in a simulator'],a:1,w:'It concerns the flight test for the type rating being passed in a simulator, for a type-rated multi-engine turbine-powered aircraft.'},
    {id:'TR03',ref:'61.775(2)',q:'For a multi-engine turbine-powered aircraft, without an applicable experience alternative, what flight time is required before exercising PIC privileges after passing the type-rating flight test in a simulator?',o:['25 hours as PIC of any turbojet aeroplane','25 hours of simulator time on the type','25 hours as pilot of an aircraft covered by the rating','25 hours as pilot of any multi-engine aircraft'],a:2,w:'The requirement is at least 25 hours of flight time as pilot of an aircraft covered by the rating. The provision does not require those 25 hours to be PIC time.'},
    {id:'TR04',ref:'61.775(2)',q:'Which privilege is specifically restricted by the 25-hour requirement in 61.775(2)?',o:['Exercising the type rating as co-pilot','Receiving flight instruction in the aircraft','Completing an approved simulator check','Exercising the type rating as pilot in command'],a:3,w:'This particular restriction applies to PIC privileges. It is not a blanket 25-hour requirement for acting as co-pilot; other applicable requirements remain.'},
    {id:'TR05',ref:'61.775(3)(a)(i)',q:'Which standalone experience threshold satisfies the turbojet alternative to the 25-hour requirement?',o:['1,000 hours as pilot of a turbojet-powered aeroplane','1,000 hours total, including 250 hours in turbojets','1,000 hours total, including 500 hours as turbojet pilot','1,000 hours of turbojet simulator time'],a:0,w:'The first turbojet alternative is at least 1,000 hours of flight time as pilot of a turbojet-powered aeroplane. It is not limited to the newly rated type.'},
    {id:'TR06',ref:'61.775(3)(a)(ii)',q:'Which combination satisfies the second turbojet experience alternative?',o:['2,000 hours total, including 250 hours as turbojet pilot','2,000 hours total, including 500 hours as turbojet pilot','1,500 hours total, including 500 hours as turbojet pilot','2,000 hours total, including 500 hours of turbojet simulator time'],a:1,w:'At least 2,000 hours of flight time must include at least 500 hours as pilot of a turbojet-powered aeroplane. Both thresholds are required.'},
    {id:'TR07',ref:'61.775(3)(a)',q:'A pilot has 2,100 hours of flight time, including 450 hours as turbojet pilot, and fewer than 25 hours on the newly rated type. Does either turbojet experience alternative apply?',o:['Yes, because total flight time exceeds 2,000 hours','Yes, because turbojet experience exceeds 400 hours','No; neither the 1,000-hour turbojet nor the 2,000/500-hour combination is met','No; the alternatives require 500 hours on the newly rated type'],a:2,w:'450 turbojet hours is below both the 1,000-hour standalone threshold and the 500-hour component of the combined alternative. Total time alone is insufficient.'},
    {id:'TR08',ref:'61.775(3)(a)(i)',q:'A pilot passed a new turbojet type-rating flight test in a simulator. They have 1,600 hours total, including 1,050 hours as turbojet pilot, but fewer than 25 hours on the new type. Is the 61.775(2) experience requirement taken to be met?',o:['No; 2,000 total hours are required in every case','No; 1,000 hours must be on the newly rated type','Yes, because more than 1,500 total hours is sufficient','Yes, through the alternative of at least 1,000 turbojet pilot hours'],a:3,w:'The two turbojet alternatives are joined by OR. Meeting the 1,000-hour turbojet alternative does not also require 2,000 total hours. This answers only the 61.775 experience requirement.'},
    {id:'TR09',ref:'61.800(1)',q:'Under 61.800(1), which activity requires a valid flight review for the pilot type rating?',o:['Exercising the rating as PIC','Completing any simulator training session','Exercising the rating only as co-pilot','Receiving a ground-school completion certificate'],a:0,w:'61.800(1) addresses exercising type-rating privileges as PIC. The full regulation also provides ways a pilot is taken to have a valid review.'},
    {id:'TR10',ref:'61.800(2)(a)',q:'Under the ordinary validity rule, when does a successfully completed type-rating flight review expire?',o:['Exactly 24 months after the date it was completed','At the end of the 24th month after the month it was completed','At the beginning of the 24th month after completion','At the end of the 12th month after the month it was completed'],a:1,w:'The ordinary rule uses the end of the 24th month after the completion month, rather than the anniversary day.'},
    {id:'TR11',ref:'61.800(2)(a)',q:'A flight review is completed on 12 September 2026. With no early-renewal carry-forward, when does it expire?',o:['12 September 2028','31 August 2028','30 September 2028','31 December 2028'],a:2,w:'September 2028 is the 24th month after September 2026. Validity extends to the end of that month.'},
    {id:'TR12',ref:'61.800(2)(b)',q:'Which conditions allow the previous flight-review expiry to be carried forward?',o:['The previous review was valid at any point in the past three months','The new review is completed within three months after the previous review expired','The previous review remains valid, regardless of how far away its expiry is','The previous review is still valid AND is due to expire within three months of the new review'],a:3,w:'Both conditions must be met. The photographed handout says OR between these conditions; the legislation uses AND.'},
    {id:'TR13',ref:'61.800(2)(b)',q:'A valid review expires on 31 December 2026. A new review is completed on 15 November 2026. Under the carry-forward rule, what is the new expiry?',o:['31 December 2028','30 November 2028','15 November 2028','31 December 2027'],a:0,w:'The previous review is still valid and expires within three months. The new expiry is the end of the 24th month after the previous expiry: 31 December 2028.'},
    {id:'TR14',ref:'61.800(4)(a)–(b)',q:'Which pair of flight tests is expressly credited as successful completion of a type-rating flight review in 61.800(4)(a)–(b)?',o:['The type-rating test, or an operational-rating test in any aircraft of the same class','The type-rating test, or an operational-rating test in an aircraft of the type covered by the pilot type rating','The type-rating test, or any licence flight test in a multi-engine aeroplane','The type-rating test, or an operational-rating theory examination'],a:1,w:'Compilation 102 specifies an aircraft of the TYPE covered by the pilot type rating for the operational-rating test. The handout uses the older CLASS wording. Other credited activities are listed later in the regulation.'},
    {id:'TR15',ref:'61.800(5A)(b); 202.291(1)',q:'An A320 type-rating holder completed a multi-engine aeroplane class flight review on 1 July 2026. It remains valid under 61.745(1A). What does 61.800(5A)(b) establish?',o:['Only the class rating has a valid flight review','The A320 type rating also has a valid instrument proficiency check','The A320 type rating is taken to have a valid flight review','The pilot no longer needs model-specific recent experience'],a:2,w:'The review also meets the A320 flight-review requirement. The 202.291(1) commencement condition is met because the review was completed on or after 30 June 2026. IFR, model-recency and other requirements remain separate.',sourceUrl:source.amendmentUrl},
    {id:'TR16',ref:'61.800(6)',q:'When does participation in an operator training and checking system satisfy 61.800(6)?',o:['Whenever the pilot is employed by an air operator','Whenever the pilot has completed the operator’s ground school','Whenever the operator conducts recurrent simulator training','When participation is successful for operations in the type AND the system has the relevant 61.040 approval'],a:3,w:'Both successful participation and the relevant CASA approval are required. Mere employment or enrolment does not meet this provision.'},
    {id:'TR17',ref:'61.800(4)(c)',q:'Which design-feature activity is credited as completing a type-rating flight review under 61.800(4)(c)?',o:['Finishing endorsement flight training in an aircraft covered by that type rating','Finishing endorsement flight training in any aircraft in the same class','Finishing only the theory component for a design-feature endorsement','Finishing a general familiarisation flight without endorsement training'],a:0,w:'The credit requires completed flight training for the endorsement in the relevant aircraft type. The photo’s class wording was changed to type on 30 June 2026.'},
    {id:'TR18',ref:'61.800(2)(a)–(b)',q:'A review expired on 31 August 2026. With no other valid review, the pilot completes a new one on 12 September 2026. When does the new review expire?',o:['31 August 2028','30 September 2028','12 September 2028','30 November 2028'],a:1,w:'The previous review had expired, so its expiry cannot be carried forward. The ordinary rule gives an expiry at the end of September 2028.'},
    {id:'TR19',ref:'61.800(2)(a)–(b)',q:'A valid review expires on 31 December 2026. The pilot completes another on 1 August 2026. When does the new review expire?',o:['31 December 2028','1 August 2028','31 August 2028','30 November 2028'],a:2,w:'The previous expiry is more than three months after the new review, so carry-forward does not apply. Ordinary validity ends on 31 August 2028.'},
    {id:'TR20',ref:'61.800(5A); 202.291(1)',q:'Under 202.291(1), which review completion dates qualify for the new flight-review credits between ratings in 61.800(5A)?',o:['Any completion date, provided the review remains valid','Only completion dates after 29 September 2026','Only completion dates before 30 June 2026','Completion dates on or after 30 June 2026'],a:3,w:'Schedule 1 commenced on 30 June 2026. Its application rule ties the new credits to reviews successfully completed from that date, including the commencement day.',sourceUrl:source.amendmentUrl},
    {"id":"TR21","ref":"61.780","q":"A type rating covers two variants and the legislative instrument requires differences training for the second. What must the pilot do before exercising the rating in that variant?","o":["Complete the prescribed differences training","Only read the second variant’s checklist","Obtain a new pilot licence","Fly one sector as PIC to establish familiarity"],"a":0,"w":"The second variant may be flown under the rating only after its prescribed differences training is completed. General competency still applies."},
    {"id":"TR22","ref":"61.385; 61.780","q":"No prescribed differences course is required for a model covered by the rating. Does that remove the general competency requirement?","o":["Yes, because the rating alone proves competence in every model","No; the pilot must still be competent in the actual aircraft’s systems, procedures, limitations and performance","Yes, provided the flight is under VFR","No; a new type-rating flight test is always mandatory"],"a":1,"w":"The absence of prescribed differences training does not waive 61.385. A new flight test is not automatically required merely because the model differs."},
    {"id":"TR23","ref":"61.785(2)","q":"In which operation may a holder exercise a multi-crew pilot type rating?","o":["Any operation if a second pilot is available on call","Single-pilot operations after 25 hours on type","Only a multi-crew operation","Single-pilot operations whenever the aircraft has an autopilot"],"a":2,"w":"61.785(2) restricts exercise of a multi-crew type rating to multi-crew operations. Flight time or an autopilot does not remove that restriction."},
    {"id":"TR24","ref":"61.785(1)","q":"Under 61.785(1), what additional qualification permits a single-pilot type-rating holder to exercise that rating in a multi-crew operation?","o":["A current medical certificate alone","A second pilot who holds an instrument rating","At least 25 hours as pilot on type","A multi-crew type rating or completion of an approved MCC course"],"a":3,"w":"The provision requires a multi-crew type rating or approved training in multi-crew cooperation. Other licence and operational conditions remain applicable."},
    {"id":"TR25","ref":"61.790","q":"What satisfies the type-specific IFR qualification condition in 61.790?","o":["The type-rating flight test was conducted under IFR, or an IPC has been completed in an aircraft covered by the rating","Any valid flight review, even if entirely VFR","Holding a type rating and having flown the model within 24 months","Completing only the instrument-rating theory examination"],"a":0,"w":"61.790 specifies the IFR flight test or subsequent IPC route. Current IPC validity, instrument privileges and other IFR requirements remain separate."},
    {"id":"TR26","ref":"61.790; 61.805","q":"A pilot has a current type-rating flight review but has never met 61.790 for that type. Does the flight review alone authorise IFR operation?","o":["Yes, every type-rating review automatically includes IFR privileges","No; the pilot must meet the type-specific IFR qualification and applicable IPC requirements","Yes, if the aircraft is IFR certified","Yes, if the pilot carries no passengers"],"a":1,"w":"Flight-review validity does not by itself satisfy 61.790 or 61.805. The pilot must also hold the appropriate underlying IFR privileges."},
    {"id":"TR27","ref":"61.795(a)","q":"Outside the approved operator-system alternative, which recent activity meets the model-recency rule?","o":["A flight review in any model in the aircraft category","A theory refresher within the last 12 months","Within the previous 24 months: exercising the rating in that model, its rating flight test or flight review, or its prescribed differences training","Any simulator session within the previous 90 days"],"a":2,"w":"The listed activities relate to the particular aircraft model. Prescribed differences training counts where required by the instrument; a generic simulator session is not itself a listed route."},
    {"id":"TR28","ref":"61.795","q":"A rating covers models A and B. The pilot recently flew A but has done none of the qualifying activities in B within 24 months and is outside an approved operator-system alternative. May the pilot rely on the recent flight in A to fly B?","o":["Yes, because both models share a rating","Yes, if the B flight is under VFR","Yes, if a class flight review is current","No; the recent-experience condition applies to the aircraft model"],"a":3,"w":"A shared rating does not remove the model-specific condition in 61.795. A valid flight review credited from another rating does not itself establish recency in B."},
    {"id":"TR29","ref":"61.795(b)","q":"What is the operator-system alternative to the listed 24-month model-recency activities?","o":["Successful participation for operations in that model in a system with the relevant 61.040 approval","Employment by an operator that owns that model","An operator identity card and current medical","Completion of ground school without the required system approval"],"a":0,"w":"Both successful participation for the model and an approval covering this regulation and operations in that model are required."},
    {"id":"TR30","ref":"61.805(2)(e)","q":"An A320 type IPC is successfully completed on 12 September 2026. With no early-renewal extension or later failed check, what is its ordinary TYPE IPC expiry under 61.805?","o":["12 September 2027","30 September 2028","12 September 2028","30 September 2027"],"a":1,"w":"The type IPC period ends at the end of the 24th month after the completion month. This does not extend separate instrument-rating, licence, recency or operator requirements."},
    {"id":"TR31","ref":"61.805(4)–(4A)","q":"A pilot with an otherwise unexpired A320 type IPC attempts but fails an aeroplane IPC listed in 61.805(4A). What happens to the type IPC validity under 61.805?","o":["It remains valid until the printed expiry","Only passenger-carrying privileges are affected","The pilot is no longer taken to have a valid type IPC for aircraft types in the aeroplane category","It remains valid for the A320 if the failed check used another aeroplane type"],"a":2,"w":"A failed category, multi-engine or type IPC listed in 61.805(4A) removes deemed type IPC validity in the category of the failed check. The original expiry does not preserve it."},
    {"id":"TR32","ref":"61.805(4B)","q":"A pilot’s type IPC is valid solely through participation in an approved operator training and checking system. For which operations is that IPC taken to be valid?","o":["All private and commercial flights in the type","Flights for any operator using the same simulator","Any operation in the same aircraft category","Only operations conducted by that operator"],"a":3,"w":"The restriction in 61.805(4B) applies when operator-system participation is the sole basis for type IPC validity."},
    {"id":"TR33","ref":"61.805(3)(b); 202.291(2)","q":"An A320 rating holder has a valid IPC under 61.805 for another multi-crew aeroplane type, completed on 1 July 2026. What does the cross-type IPC provision establish?","o":["The A320 type IPC requirement can be met; other IFR, model-recency and operator requirements remain","The pilot gains an A320 type rating automatically","The pilot gains single-pilot authority for the A320","The pilot may disregard a subsequent failed aeroplane IPC"],"a":0,"w":"61.805(3)(b) recognises a valid IPC for another multi-crew type in the same aircraft category. The July 2026 completion satisfies the application-date condition."},
    {"id":"TR34","ref":"202.291(2)","q":"Which statement correctly describes the application rule for the June 2026 amendments to 61.805?","o":["Every listed event must have occurred on or after 30 June 2026","IPCs must be completed on or after 30 June 2026; specified flight tests, operator checks, system participation and approvals may be before, on or after that date","Every IPC completed before 30 June 2026 is automatically cancelled","Only flight tests completed after 29 September 2026 qualify"],"a":1,"w":"202.291(2) distinguishes IPC completion dates from the other listed events. It does not simply cancel every earlier IPC or use the September commencement date.","sourceUrl":"https://www.legislation.gov.au/F1998B00220/2026-06-30/2026-06-30/text/original/pdf/5"},
    {"id":"TR35","ref":"61.805(5)–(6)","q":"For the IPC-completion routes in 61.805(2)(e) and (f), which statement is correct?","o":["An unassessed simulator practice session is sufficient","A written knowledge examination alone is sufficient","The check may use a relevant aircraft or an approved flight simulation training device, with the required assessment and licence endorsement","Only a check flown in the actual aircraft can count"],"a":2,"w":"61.805(5) sets the assessment and licence-endorsement requirements; (6) permits a relevant aircraft or an approved flight simulation training device for the check."},
    {"id":"TR36","ref":"61.770; 61.795; 61.800; 61.805","q":"A pilot’s MEA class review gives valid A320 flight-review credit under 61.800(5A). Which conclusion is correct?","o":["The pilot automatically gains A320 model recency","The pilot automatically gains a valid A320 IPC","The pilot may conduct any A320 operation regardless of licence conditions","The credit satisfies the flight-review requirement only; all other applicable requirements still need to be met"],"a":3,"w":"Flight-review credit is not a grant of a type rating, model recency, IFR currency or operator authorisation. The existing licence and type-rating limitations still apply."}
  ];
  function shuffle(items,random=Math.random){const a=items.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  function buildDeck(count,random=Math.random){return shuffle(questions,random).slice(0,count).map(q=>({...q,choices:shuffle(q.o.map((text,index)=>({text,index})),random)}));}
  function resultFor(deck,answers){const answered=deck.filter(q=>Number.isInteger(answers[q.id])).length;const correct=deck.filter(q=>answers[q.id]===q.a).length;return {answered,correct,total:deck.length,complete:answered===deck.length&&deck.length>0,passed:answered===deck.length&&deck.length>0&&correct/deck.length>=0.8};}
  const api={source,questions,buildDeck,resultFor};
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  root.TypeRatings=api;
  if(typeof document==='undefined')return;
  const $=id=>document.getElementById(id);
  let deck=[],answers={},position=0,mode='learn';
  function start(){mode=$('feedbackMode').value;deck=buildDeck(Number($('runLength').value));answers={};position=0;$('setup').hidden=true;$('notes').hidden=true;$('results').hidden=true;$('quiz').hidden=false;render();}
  function render(){const q=deck[position];$('quizProgress').textContent=`${mode==='exam'?'Exam':'Learn'} · Question ${position+1} of ${deck.length}`;$('question').textContent=q.q;$('choices').replaceChildren();$('feedback').hidden=true;$('next').hidden=true;$('next').textContent=position===deck.length-1?'See results':'Next question';
    q.choices.forEach(choice=>{const button=document.createElement('button');button.className='choice';button.textContent=choice.text;button.onclick=()=>answer(choice.index);$('choices').appendChild(button);});$('question').focus();
  }
  function answer(index){const q=deck[position];if(Object.hasOwn(answers,q.id))return;answers[q.id]=index;
    [...$('choices').children].forEach((button,i)=>{button.disabled=true;const original=q.choices[i].index;if(mode==='learn'&&original===q.a)button.classList.add('correct');if(original===index){button.classList.add('selected');if(mode==='learn'&&index!==q.a)button.classList.add('incorrect');}});
    $('feedback').hidden=false;$('feedback').textContent=mode==='exam'?'Answer recorded. Feedback will appear after the last question.':`${index===q.a?'Correct.':'Incorrect. Correct answer: '+q.o[q.a]+'.'} ${q.w} · CASR ${q.ref}`;$('next').hidden=false;$('next').focus();
  }
  function finish(){const result=resultFor(deck,answers);if(!result.complete)return;$('quiz').hidden=true;$('results').hidden=false;$('score').textContent=`${result.correct} / ${result.total} — ${result.passed?'Pass':'Keep practising'}`;$('scoreNote').textContent=`${Math.round(result.correct/result.total*100)}% · Practice pass mark 80% · Every answer reviewed below.`;$('answerReview').replaceChildren();
    deck.forEach(q=>{const card=document.createElement('article');card.className='review-card';const title=document.createElement('h3');title.textContent=(answers[q.id]===q.a?'Correct · ':'Review · ')+q.q;const selected=document.createElement('p');selected.textContent='Your answer: '+q.o[answers[q.id]];const correct=document.createElement('p');correct.textContent='Correct answer: '+q.o[q.a];const why=document.createElement('p');why.textContent=q.w;const ref=document.createElement('a');ref.href=q.sourceUrl||source.url;ref.textContent='CASR '+q.ref;card.append(title,selected,correct,why,ref);$('answerReview').appendChild(card);});$('score').focus();
  }
  $('begin').onclick=start;$('again').onclick=start;$('next').onclick=()=>{if(!Object.hasOwn(answers,deck[position].id))return;if(position===deck.length-1)finish();else{position++;render();}};
  function back(){deck=[];answers={};$('quiz').hidden=true;$('results').hidden=true;$('setup').hidden=false;$('notes').hidden=false;$('moduleTitle').focus();}
  $('exitQuiz').onclick=back;$('backToStudy').onclick=back;
  if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
})(typeof window!=='undefined'?window:globalThis);
